export const NEW_EXERCISE_STARTED = "NEW_EXERCISE_STARTED";
export const NEW_EXERCISE_SUCCEEDED = "NEW_EXERCISE_SUCCEEDED";

export const GET_EXERCISES_STARTED = "GET_EXERCISES_STARTED";
export const GET_EXERCISES_SUCCEEDED = "GET_EXERCISES_SUCCEEDED";

export const GET_EXERCISE_STARTED = "GET_EXERCISE_STARTED";
export const GET_EXERCISE_SUCCEEDED = "GET_EXERCISE_SUCCEEDED";

export const EDIT_EXERCISE_STARTED = "EDIT_EXERCISE_STARTED";
export const EDIT_EXERCISE_SUCCEEDED = "EDIT_EXERCISE_SUCCEEDED";

export const SET_MUSCLE_GROUP = "SET_MUSCLE_GROUP";

export const GET_MUSCLE_GROUPS_STARTED = "GET_MUSCLE_GROUPS_STARTED";
export const GET_MUSCLE_GROUPS_SUCCEEDED = "GET_MUSCLE_GROUPS_SUCCEEDED";