export const NEW_EXERCISE_STARTED = "SET_EXERCISE_STARTED";
export const NEW_EXERCISE_SUCCEEDED = "SET_EXERCISE_SUCCEEDED";

export const GET_EXERCISES_STARTED = "GET_EXERCISES_STARTED";
export const GET_EXERCISES_SUCCEEDED = "GET_EXERCISES_SUCCEEDED";
export const GET_EXERCISES_FAILED = "GET_EXERCISES_FAILED";

export const GET_EXERCISE_STARTED = "GET_EXERCISE_STARTED";
export const GET_EXERCISE_SUCCEEDED = "GET_EXERCISE_SUCCEEDED";

export const EDIT_EXERCISE_STARTED = "EDIT_EXERCISE_STARTED";
export const EDIT_EXERCISE_SUCCEEDED = "EDIT_EXERCISE_SUCCEEDED";

export const SET_MUSCLE_GROUP = "SET_MUSCLE_GROUP";

export const GET_MUSCLE_GROUPS_STARTED = "GET_MUSCLE_GROUPS_STARTED";
export const GET_MUSCLE_GROUPS_SUCCEEDED = "GET_MUSCLE_GROUPS_SUCCEEDED";

export const SET_TARGET = "SET_TARGET";

export const GET_TARGETS_STARTED = "GET_TARGETS_STARTED";
export const GET_TARGETS_SUCCEEDED = "GET_TARGETS_SUCCEEDED";

export const NEW_MUSCLE_STARTED = "NEW_MUSCLE_STARTED";
export const NEW_MUSCLE_SUCCEEDED = "NEW_MUSCLE_SUCCEEDED";

export const GET_MUSCLES_STARTED = "GET_MUSCLES_STARTED";
export const GET_MUSCLES_SUCCEEDED = "GET_MUSCLES_SUCCEEDED";

export const GET_MUSCLE_STARTED = "GET_MUSCLE_STARTED";
export const GET_MUSCLE_SUCCEEDED = "GET_MUSCLE_SUCCEEDED";

export const EDIT_MUSCLE_STARTED = "EDIT_MUSCLE_STARTED";
export const EDIT_MUSCLE_SUCCEEDED = "EDIT_MUSCLE_SUCCEEDED";

export const GET_ROUTINES_STARTED = "GET_ROUTINES_STARTED";
export const GET_ROUTINES_SUCCEEDED = "GET_ROUTINES_SUCCEEDED";
export const GET_ROUTINES_FAILED = "GET_ROUTINES_FAILED";
