export const NEW_EXERCISE_STARTED = "NEW_EXERCISE_STARTED";
export const NEW_EXERCISE_SUCCEEDED = "NEW_EXERCISE_SUCCEEDED";

export const GET_EXERCISES_STARTED = "EXERCISES_STARTED";
export const GET_EXERCISES_SUCCEEDED = "EXERCISES_SUCCEEDED";